Categories:
  - Habit Tracker
  - Role-Playing Game
License: GPL-3.0-only
AuthorName: hellArcom
SourceCode: https://github.com/hellArcom/life_rpg
IssueTracker: https://github.com/hellArcom/life_rpg/issues
Changelog: https://github.com/hellArcom/life_rpg/releases

AutoName: Life RPG

RepoType: git
Repo: https://github.com/hellArcom/life_rpg.git

Builds:
  - versionName: 0.5.0
    versionCode: 11
    commit: bccb21e010926ec3ffe26148ed9c872534a4d42d
    output: build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk
    srclibs:
      - flutter@stable
    rm:
      - ios
      - linux
      - windows
    prebuild:
      - flutterVersion=3.44.9
      - '[[ $flutterVersion ]]'
      - git -C $$flutter$$ checkout -f $flutterVersion
      - $$flutter$$/bin/flutter config --no-analytics
      - export PUB_CACHE=$(pwd)/.pub-cache
      - $$flutter$$/bin/flutter pub get --enforce-lockfile
    scandelete:
      - .pub-cache
    build:
      - export PUB_CACHE=$(pwd)/.pub-cache
      - $$flutter$$/bin/flutter build apk --release --split-per-abi --target-platform="android-arm"

  - versionName: 0.5.0
    versionCode: 12
    commit: bccb21e010926ec3ffe26148ed9c872534a4d42d
    output: build/app/outputs/flutter-apk/app-arm64-v8a-release.apk
    srclibs:
      - flutter@stable
    rm:
      - ios
      - linux
      - windows
    prebuild:
      - flutterVersion=3.44.9
      - '[[ $flutterVersion ]]'
      - git -C $$flutter$$ checkout -f $flutterVersion
      - $$flutter$$/bin/flutter config --no-analytics
      - export PUB_CACHE=$(pwd)/.pub-cache
      - $$flutter$$/bin/flutter pub get --enforce-lockfile
    scandelete:
      - .pub-cache
    build:
      - export PUB_CACHE=$(pwd)/.pub-cache
      - $$flutter$$/bin/flutter build apk --release --split-per-abi --target-platform="android-arm64"

  - versionName: 0.5.0
    versionCode: 13
    commit: bccb21e010926ec3ffe26148ed9c872534a4d42d
    output: build/app/outputs/flutter-apk/app-x86_64-release.apk
    srclibs:
      - flutter@stable
    rm:
      - ios
      - linux
      - windows
    prebuild:
      - flutterVersion=3.44.9
      - '[[ $flutterVersion ]]'
      - git -C $$flutter$$ checkout -f $flutterVersion
      - $$flutter$$/bin/flutter config --no-analytics
      - export PUB_CACHE=$(pwd)/.pub-cache
      - $$flutter$$/bin/flutter pub get --enforce-lockfile
    scandelete:
      - .pub-cache
    build:
      - export PUB_CACHE=$(pwd)/.pub-cache
      - $$flutter$$/bin/flutter build apk --release --split-per-abi --target-platform="android-x64"

AutoUpdateMode: Version
UpdateCheckMode: Tags
VercodeOperation:
  - 10 * %c + 1
  - 10 * %c + 2
  - 10 * %c + 3
UpdateCheckData: pubspec.yaml|version:\s.+\+(\d+)|.|version:\s(.+)\+
CurrentVersion: 0.5.0
CurrentVersionCode: 13
